raw script

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -13,15 +13,10 @@ jobs:
       - name: Beta Dependencies Check
         run: >
           set -e
-          check_files() {
-              has_error=0
-              for file in "$@" ; do
-                  if egrep "3.3.0" $file; then
-                      echo "ERROR: $file should not have a yalc dependency"
-                      has_error=1
-                  fi
-              done
-          }
-          check_files "$@"
-          exit $has_error
+          for file in "$@" ; do
+              if egrep "3.3.0" $file; then
+                  echo "ERROR: $file should not have a yalc dependency"
+                  exit 1
+              fi
+          done
         shell: bash
